apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.product_name}}
  description: {{cookiecutter.product_description}}
  annotations: 
    github.com/project-slug: {{cookiecutter.destination.git.owner + "/" + cookiecutter.destination.git.name}}
    backstage.io/source-ref: {{cookiecutter.storePath | jsonify}}
    backstage.io/techdocs-ref: url:{{cookiecutter.storePath}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner}}